### PR TITLE
Changed hard Coded Paths in HideAPI.scala

### PR DESCRIPTION
**Pull request by kaushin**

### CODE REVIEW

**Comment by fgwei** [comment]
I already help you fixed the hard coded problem and performance problem, and changed you file to:
https://github.com/sireum/amandroid/blob/master/sireum-amandroid-run/src/main/scala/org/sireum/amandroid/run/csm/HideIconAPI_run.scala
and
...droid-security/src/main/scala/org/sireum/amandroid/security/apiMisuse/HideIconAPIMisuse.scala

So don't need to have this pull request.

**Comment by fgwei** [comment]
You can just sync with the amandroid repo, and use the one I modified.
And the file name I changed from:
HideAPI_run.scala -> HideIconAPI_run.scala
HideAPIMisuse.scala -> HideIconAPIMisuse.scala

**Comment by kaushin** [comment]
Yes , sorry for the trouble. and Thank you.

**Comment by fgwei** [comment]
Thank you for your contribution :D

**Pull request closed without merging**
